"""
ReAct-MAS: Unstructured LLM Multi-Agent System Baseline.

References:
  Yao, S. et al. (2023). ReAct: Synergizing reasoning and acting in language models.
  ICLR 2023. arXiv:2210.03629.
  Wang, L. et al. (2024). A survey on LLM-based autonomous agents.
  Frontiers of Computer Science, 18(6).

Architecture:
  Each participating agent runs a Thought → Action → Observation (ReAct) loop.
  Proposals and votes are generated by the LLM without a formal utility function,
  deterministic safeguard, or structured rejection schema.

  Round structure:
    1. Lead Agent (THOUGHT → PROPOSE): generates candidate actions as free text.
    2. Peer Agents (THOUGHT → VOTE): each independently decides accept/reject.
    3. Lead Agent (THOUGHT → REFINE or COMMIT): reads peer votes and acts.
  Up to R_max rounds.

Key differences from DANCER (ablation dimensions):
  ✗ No formal utility decomposition L_k(p)
  ✗ No structured rejection reasons (free text only → noisy signal)
  ✗ No Deterministic Safeguard Layer (hallucinations can propagate)
  ✗ No bounded termination guarantee (no temporal decay)
  ✗ No registry discovery mechanism (agents fixed at construction)
  ✓ LLM-powered (same model as DANCER's Cognitive Layer)
  ✓ Multi-agent (peer voting)

Cost note: ReAct-MAS issues O(R_max × n) LLM calls per episode vs DANCER's O(R_max)
  inference calls (centralized generation). ReAct-MAS is therefore more expensive
  at scale even for the same model.
"""
from __future__ import annotations

import json
import os
import re
import time
from typing import List, Optional, Tuple, Dict

from openai import OpenAI

from core.models import Proposal, ShippingMethod, RunResult
from core.agents import IPAgent

_VALID_METHODS = {m.value for m in ShippingMethod}
_R_MAX = 5          # same R_max as DANCER; loop executes R_max+1 = 6 evaluation
                    # rounds, matching DANCER's rounds 0..R_max (audit F9: the
                    # original range(5) gave ReAct one fewer evaluation round)


# ── LLM client ───────────────────────────────────────────────────────────────

def _get_client() -> Tuple[OpenAI, str]:
    if os.environ.get("DANCER_BASE_URL"):
        client = OpenAI(
            api_key=os.environ.get("DANCER_API_KEY", "dummy"),
            base_url=os.environ["DANCER_BASE_URL"],
        )
    elif os.environ.get("OPENROUTER_API_KEY"):
        client = OpenAI(
            api_key=os.environ["OPENROUTER_API_KEY"],
            base_url="https://openrouter.ai/api/v1",
        )
    elif os.environ.get("OPENAI_API_KEY"):
        client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    else:
        raise EnvironmentError("No API key found. Set OPENROUTER_API_KEY or OPENAI_API_KEY.")
    model = os.environ.get("DANCER_MODEL", "openai/gpt-4o-mini")
    return client, model


def _llm_call(client: OpenAI, model: str, system: str, user: str,
               use_json: bool = False) -> Tuple[str, int]:
    kwargs: dict = {
        "model": model,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user",   "content": user},
        ],
        "temperature": 0.7,
        "max_tokens": 600,
    }
    if use_json:
        kwargs["response_format"] = {"type": "json_object"}
    try:
        resp = client.chat.completions.create(**kwargs)
    except Exception:
        kwargs.pop("response_format", None)
        resp = client.chat.completions.create(**kwargs)
    text = resp.choices[0].message.content or ""
    tokens = resp.usage.total_tokens if resp.usage else len(text) // 4
    return text, tokens


# ── ReAct prompts ────────────────────────────────────────────────────────────

_LEAD_SYSTEM = """\
You are the Lead Agent in a multi-agent supply-chain disruption response team.
Use the ReAct (Reason + Act) pattern:
  THOUGHT: <one sentence of reasoning>
  ACTION: <JSON object with fields: proposals (list of objects with method, cost_normalized [0-1], time_days, description)>

Allowed method values: Standard_Shipping | Express_Air_Freight | Consolidated_Rail |
  Land_Transport | Third_Party_Logistics | Alternative_Port_B | Expedited_Ground

Proposals must respect the market feasibility envelopes given in the user
message — out-of-envelope (cost, time) values are rejected as infeasible.

Output ONLY the THOUGHT and ACTION lines. No other text."""

_PEER_SYSTEM = """\
You are a Peer Agent evaluating supply-chain disruption proposals from the Lead Agent.
Use the ReAct pattern:
  THOUGHT: <brief reasoning about whether the proposal meets your constraints>
  ACTION: {"vote": "ACCEPT" or "REJECT", "reason": "<one sentence>"}

Be conservative: reject if cost or time appears unfeasible. Output ONLY THOUGHT and ACTION."""

_REFINE_SYSTEM = """\
You are the Lead Agent refining proposals based on peer feedback.
Use the ReAct pattern:
  THOUGHT: <reasoning about what constraints were violated>
  ACTION: <JSON object: proposals (list of revised proposals targeting the violations)>

Proposals must respect the market feasibility envelopes given in the user
message — out-of-envelope (cost, time) values are rejected as infeasible.

Output ONLY THOUGHT and ACTION. Allowed methods: Standard_Shipping | Express_Air_Freight |
Consolidated_Rail | Land_Transport | Third_Party_Logistics | Alternative_Port_B | Expedited_Ground"""


# ── Parsing helpers ───────────────────────────────────────────────────────────

def _parse_action_json(text: str) -> Optional[dict]:
    """Extract JSON from ACTION: line."""
    # Try to find ACTION: {...} or ACTION: [...]
    m = re.search(r"ACTION:\s*(\{.*\}|\[.*\])", text, re.DOTALL)
    if not m:
        m = re.search(r"\{.*\}", text, re.DOTALL)
    if not m:
        return None
    try:
        return json.loads(m.group(1) if m.lastindex else m.group())
    except json.JSONDecodeError:
        try:
            # Try broader match
            all_json = re.findall(r"\{[^{}]+\}", text)
            for j in all_json:
                try:
                    return json.loads(j)
                except Exception:
                    continue
        except Exception:
            pass
    return None


def _parse_proposals_from_action(action: dict, round_num: int) -> List[Proposal]:
    """Extract Proposal objects from a ReAct ACTION dict."""
    raw = action.get("proposals", [])
    if isinstance(raw, dict):
        raw = [raw]
    proposals = []
    for i, item in enumerate(raw):
        try:
            method = item.get("method", "Standard_Shipping")
            if method not in _VALID_METHODS:
                method = "Standard_Shipping"
            cost = max(0.0, min(1.0, float(item.get("cost_normalized", 0.5))))
            time_d = max(0.1, float(item.get("time_days", 3.0)))
            desc = str(item.get("description", f"ReAct proposal r{round_num}_{i}"))
            proposals.append(Proposal(
                id=f"react_r{round_num}_{i}",
                method=ShippingMethod(method),
                cost_normalized=cost,
                time_days=time_d,
                description=desc,
                requires_new_agent=False,
                new_agent_id=None,
            ))
        except Exception:
            continue
    return proposals


def _majority_accept(votes: List[dict]) -> Tuple[bool, float]:
    """True if strict majority of votes are ACCEPT."""
    accepts = sum(1 for v in votes if v.get("vote", "").upper() == "ACCEPT")
    ratio = accepts / max(1, len(votes))
    return ratio > 0.5, ratio


# ── Public runner ─────────────────────────────────────────────────────────────

def run_react_mas(
    scenario: str,
    agent_dicts: List[dict],
    active_agent_ids: List[str],
    registry: List[dict],
    disruption_type: str,
    iteration: int = 0,
    tau_min: float = 0.45,
) -> RunResult:
    """Execute one ReAct-MAS episode.

    Each round:
      1. Lead Agent: THOUGHT + PROPOSE (1 LLM call)
      2. Each Peer Agent: THOUGHT + VOTE (n-1 LLM calls)
      3. If majority accept AND a proposal clears the CANONICAL criterion
         (mean utility over the shared agent set >= tau_min — identical to
         every other system, audit F3) → commit. Else → Lead refines.

    AUDIT F3: the previous commit gate required UNANIMOUS individual
    acceptance, which the unavailable carrier could never give on structural
    failures — a guaranteed 0% by construction, not an LLM limitation.
    """
    start = time.time()
    total_tokens = 0
    msgs = 0
    client, model = _get_client()

    active_set = set(active_agent_ids)
    agents: List[IPAgent] = [IPAgent.from_dict(d) for d in agent_dicts
                              if d["agent_id"] in active_set]
    if not agents:
        return RunResult(scenario=scenario, system="ReAct-MAS", iteration=iteration,
                         success=False, rounds=0, messages_sent=0, total_tokens=0,
                         final_utility=0.0, latency_seconds=time.time() - start)

    lead = agents[0]
    peers = agents[1:]

    # Context shared across rounds (no structured rejection — free text only)
    history: List[str] = []
    current_proposals: List[Proposal] = []
    final_round = 0

    for rnd in range(_R_MAX + 1):    # rounds 0..R_max — same budget as DANCER
        final_round = rnd + 1

        # ── Step 1: Lead Agent proposes ───────────────────────────────
        from core.proposal_envelopes import envelope_prompt_block
        if rnd == 0:
            user_prompt = (
                f"Disruption: {disruption_type}\n"
                f"Active agents: {[a.agent_id for a in agents]}\n"
                f"Goal: Restore supply-chain choreography.\n"
                f"{envelope_prompt_block()}\n"
                "Generate 2-3 logistics proposals."
            )
        else:
            peer_feedback = "\n".join(history[-len(peers):]) if history else "No feedback yet."
            user_prompt = (
                f"Disruption: {disruption_type}\n"
                f"Previous proposals were rejected. Peer feedback:\n{peer_feedback}\n"
                f"{envelope_prompt_block()}\n"
                "Generate revised proposals that address the rejection reasons."
            )

        text, tok = _llm_call(client, model, _LEAD_SYSTEM, user_prompt)
        total_tokens += tok
        msgs += 1   # Lead broadcast

        action = _parse_action_json(text)
        if action is None:
            continue
        current_proposals = _parse_proposals_from_action(action, rnd)
        if not current_proposals:
            continue

        # ── Step 2: Peer Agents vote (individual LLM calls — no formal utility) ──
        votes: List[dict] = []
        for peer in peers:
            proposals_text = "\n".join(
                f"  - Method: {p.method.value}, Cost: {p.cost_normalized:.2f}, "
                f"Time: {p.time_days:.1f}d, Desc: {p.description}"
                for p in current_proposals
            )
            peer_prompt = (
                f"You are {peer.agent_id} (role: {peer.role}).\n"
                f"Your constraints: max_cost={peer.max_cost:.2f}, "
                f"max_delay={peer.max_delay_days:.1f} days.\n"
                f"Proposals from Lead:\n{proposals_text}\n"
                "Vote ACCEPT if at least one proposal is feasible, REJECT otherwise."
            )
            vote_text, vote_tok = _llm_call(client, model, _PEER_SYSTEM, peer_prompt)
            total_tokens += vote_tok
            msgs += 1   # peer response

            vote_action = _parse_action_json(vote_text)
            if vote_action and "vote" in vote_action:
                votes.append({"agent": peer.agent_id,
                               "vote": vote_action["vote"],
                               "reason": vote_action.get("reason", "")})
                history.append(f"{peer.agent_id}: {vote_action.get('reason', '')}")
            else:
                # Parse failure → treat as reject
                votes.append({"agent": peer.agent_id, "vote": "REJECT",
                               "reason": "parse failure"})

        # ── Step 3: Consensus check ───────────────────────────────────
        # MECHANISM/CRITERION separation (audit F3, revised): ReAct-MAS has
        # no formal utility machinery — its internal commit mechanism is the
        # majority vote ALONE. On majority-accept, the Lead commits its
        # top-ranked proposal (list order = the LLM's own ranking). The
        # canonical criterion then only RECORDS whether that committed
        # proposal succeeds; it never feeds back into the loop. (Giving
        # ReAct a canonical commit gate would hand it DANCER's Deterministic
        # Safeguard function and invalidate the comparison.)
        accepted, ratio = _majority_accept(votes)
        if accepted and current_proposals:
            from core.evaluation import canonical_outcome
            committed = current_proposals[0]
            outcome = canonical_outcome(committed, agent_dicts, registry,
                                        tau_min,
                                        active_agent_ids=active_agent_ids,
                                        disruption_type=disruption_type)
            return RunResult(
                scenario=scenario, system="ReAct-MAS", iteration=iteration,
                success=outcome.success, rounds=final_round,
                messages_sent=msgs, total_tokens=total_tokens,
                final_utility=outcome.aggregate_utility,
                latency_seconds=time.time() - start,
                proposal_method=committed.method.value,
                proposal_cost=committed.cost_normalized,
                proposal_time=committed.time_days,
                proposal_new_agent=committed.new_agent_id,
                n_accepting=outcome.n_individually_accepting,
            )

    # Max rounds exceeded — no committed solution.
    return RunResult(
        scenario=scenario, system="ReAct-MAS", iteration=iteration,
        success=False, rounds=final_round, messages_sent=msgs,
        total_tokens=total_tokens, final_utility=0.0,
        latency_seconds=time.time() - start,
    )
